import oacensus.scrapers.biomedcentral
import oacensus.scrapers.crossref
import oacensus.scrapers.csvfile
import oacensus.scrapers.demo
import oacensus.scrapers.doaj
import oacensus.scrapers.doilist
import oacensus.scrapers.elsevier
import oacensus.scrapers.excelfile
import oacensus.scrapers.licenses
import oacensus.scrapers.oag
import oacensus.scrapers.oai
import oacensus.scrapers.orcids
import oacensus.scrapers.pubmed
import oacensus.scrapers.rcukgtr
import oacensus.scrapers.scimago
import oacensus.scrapers.wiley

import oacensus.reports.excel_dump
import oacensus.reports.oa_excel
import oacensus.reports.text_dump
import oacensus.reports.personal_openness
import oacensus.reports.institution
